application: ranking-survey
runtime: go
api_version: go1
version: master

handlers:
- url: /static
  static_dir: static
- url: /questions.csv
  login: admin
  script: _go_app
- url: /.*
  script: _go_app
